### ISSUE TITLE
Add the `keywords` field and the `categories` field to the `Cargo.toml`

### ISSUE THREAD

**Issue by sorairolake** [ducaale/xh#238]
The [`keywords`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-keywords-field) field and the [`categories`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-categories-field) field can help when searching for the package on a registry.

Example:

```toml
keywords = ["http"]
categories = ["command-line-utilities"]
```
