### ISSUE TITLE
Downloading is slow

### ISSUE THREAD

**Issue by svenstaro** [ducaale/xh#49]
Hey, cool tool. :)

I noticed that downloading is pretty slow as compared to `wget`. For instance, on downloading a random large file, using `ht -d` I get 7-13MB/s on repeated tests while using `wget` I get a good 60MB/s (my full connection speed). Any idea?

Sorry I can't be more specific but literally all I do is a multi-run test of a 2-5GB-sized file between `wget` and `ht -d`.

**Comment by blyxxyz** [comment]
Hm, I can't reproduce this myself.

Does it happen when downloading from localhost?

Does it happen with a trivial `reqwest`-based downloader? e.g.

`main.rs`
```rust
fn main() {
    let url = std::env::args().nth(1).unwrap();
    let out = std::env::args().nth(2).unwrap();
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .open(&out)
        .unwrap();
    reqwest::blocking::get(&url)
        .unwrap()
        .copy_to(&mut file)
        .unwrap();
}
```

`Cargo.toml`
```toml
[package]
name = "simpledl"
version = "0.0.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls", "stream", "json", "gzip", "brotli", "multipart"] }
```
(features copied from `ht`'s, plus `blocking`)
